# -*- coding: utf-8 -*-
# Generated by Django 1.11.7.dev20171113182819 on 2017-11-13 20:49
from __future__ import unicode_literals

from django.db import migrations, models
import appdj.projects.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_project_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectfile',
            name='file',
            field=models.FileField(max_length=255, upload_to=lambda x: x),
        ),
    ]
