# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-05 15:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_merge_20171128_0832'),
        ('projects', '0009_auto_20171129_1541'),
    ]

    operations = [
    ]
