# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-14 13:48
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations
from django.contrib.postgres.operations import BtreeGinExtension


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_auto_20180116_1227'),
    ]

    operations = [
        BtreeGinExtension(),
        migrations.AddField(
            model_name='project',
            name='config',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
    ]
