# Generated by Django 2.1.8 on 2019-03-15 10:16

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_auto_20180914_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='config',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
