# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-10-16 10:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'permissions': (('read_group', 'Read group'), ('write_group', 'Write group'), ('add_member', 'Add member'), ('remove_member', 'Remove member'))},
        ),
        migrations.AddField(
            model_name='group',
            name='private',
            field=models.BooleanField(default=True),
        ),
    ]
