# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-10-16 10:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_auto_20171016_1037'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='group',
            unique_together=set([('team', 'name')]),
        ),
    ]
