# -*- coding: utf-8 -*-
# Generated by Django 1.11.4.dev20170705124151 on 2017-07-05 15:58
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20170519_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='address',
            field=models.CharField(max_length=255),
        ),

        migrations.AddField(
            model_name='email',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),

    ]
