# -*- coding: utf-8 -*-
# Generated by Django 1.11.4.dev20170707175030 on 2017-07-10 10:38
from __future__ import unicode_literals

from django.db import migrations
import uuid


def gen_uuid(apps, schema_editor):
    UserEmail = apps.get_model('users', 'Email')
    for row in UserEmail.objects.all():
        row.id = uuid.uuid4()
        row.save(update_fields=['uuid'])


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20170705_1558'),
    ]

    operations = [
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop)
    ]
