# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-10 14:13
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_userprofile_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='config',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}),
        ),
    ]
