# -*- coding: utf-8 -*-
# Generated by Django 1.11.4.dev20170707175030 on 2017-07-10 10:38
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20170710_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='email',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.RenameField(
            model_name='email',
            old_name='uuid',
            new_name='id',
        ),
    ]

