# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-09-14 09:51
from __future__ import unicode_literals

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20180510_1413'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='user',
            index=django.contrib.postgres.indexes.GinIndex(fields=['username', 'email', 'first_name', 'last_name'], name='users_user_usernam_559e2c_gin'),
        ),
    ]
