# -*- coding: utf-8 -*-
# Generated by Django 1.11.4.dev20170804115648 on 2017-08-07 11:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_auto_20170714_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='plan',
            name='amount',
            field=models.PositiveIntegerField(help_text='Amount, in cents (or equivalent) the plan should cost. For example, a value of 500 -> $5.00'),
        ),
    ]
