# Generated by Django 2.1.8 on 2019-03-19 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oauth2_provider', '0003_auto_20190313_0854'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accesstoken',
            name='application'
        ),
    ]
