# -*- coding: utf-8 -*-
# Generated by Django 1.11.5.dev20170815122426 on 2017-08-15 15:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectfile',
            name='public',
        ),
    ]
