# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-10-13 12:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_copying_enabled'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectfile',
            options={'permissions': (('write_project_file', 'Write project file'), ('read_project_file', 'Read project file'))},
        ),
    ]
