# -*- coding: utf-8 -*-
# Generated by Django 1.11.6.dev20171101121058 on 2017-11-01 13:21
from __future__ import unicode_literals

from django.db import migrations
import projects.models
import projects.storage


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_project_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectfile',
            name='file',
            field=projects.models.TbsFileField(storage=projects.storage.TbsStorage(), upload_to=projects.models.project_directory_path),
        ),
    ]
