# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-01-16 11:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_django', '0002_auto_20171030_1234'),
        ('projects', '0010_merge_20171205_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='social_integrations',
            field=models.ManyToManyField(to='social_django.UserSocialAuth'),
        ),
    ]
