# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-01-16 11:35
from __future__ import unicode_literals

from django.db import migrations


def migrate_sync(apps, schema_editor):
    Project = apps.get_model('projects', 'Project')
    for project in Project.objects.all():
        integrations = list(project.integrations.all())
        project.synced_integrations.add(*integrations)


def reverse(apps, schema_editor):
    Project = apps.get_model('projects', 'Project')
    for project in Project.objects.all():
        integrations = list(project.synced_integrations.all())
        project.integrations.add(*integrations)


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_project_social_integrations'),
    ]

    operations = [
        migrations.RunPython(migrate_sync, reverse)
    ]
