# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-01-16 12:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_remove_project_integrations'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='social_integrations',
            new_name='integrations',
        ),
    ]
