# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-01-16 12:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_auto_20180116_1203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectfile',
            name='author',
        ),
        migrations.RemoveField(
            model_name='projectfile',
            name='project',
        ),
        migrations.RemoveField(
            model_name='syncedresource',
            name='integration',
        ),
        migrations.RemoveField(
            model_name='syncedresource',
            name='project',
        ),
        migrations.AlterField(
            model_name='project',
            name='integrations',
            field=models.ManyToManyField(related_name='projects', to='social_django.UserSocialAuth'),
        ),
        migrations.DeleteModel(
            name='ProjectFile',
        ),
        migrations.DeleteModel(
            name='SyncedResource',
        ),
    ]
