# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-03-11 12:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('triggers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trigger',
            name='cause',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cause_triggers', to='actions.Action'),
        ),
        migrations.AlterField(
            model_name='trigger',
            name='effect',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='effect_triggers', to='actions.Action'),
        ),
    ]
