dist: xenial

language: python
python:
  - "3.8"

services:
  - docker
jobs:
  include:
    - name: "Django Test"
      before_script:
        - docker-compose -v
        - docker -v
        - docker-compose -f local.yml build
        # Ensure celerybeat does not crash due to non-existent tables
        - docker-compose -f local.yml run --rm django python manage.py migrate
        - docker-compose -f local.yml up -d
      script:
        - docker-compose -f local.yml run django pytest
      after_failure:
        - docker-compose -f local.yml logs
    - name: "Linter"
      before_script:
        - python3 -m pip install -r requirements/local.txt
      script:
        - docker-compose -f local.yml run --rm webapp flake8 illumidesk
        - docker-compose -f local.yml run --rm webapp pylint illumidesk
  jobs:
    include:
      - stage: release
        deploy:
          provider: script
          skip_cleanup: true
          script:
            - nvm install lts/*
            - npx semantic-release
          on:
            all_branches: true
