# -*- coding: utf-8 -*-
# Generated by Django 1.11.4.dev20170712103359 on 2017-07-12 17:03
from __future__ import unicode_literals
import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(model_name="user",
                              name="username",
                              field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
    ]
