# Generated by Django 2.2.1 on 2019-08-09 11:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('name', models.CharField(default='', max_length=100, verbose_name='Name')),
                ('client_type', models.CharField(choices=[('confidential', 'Confidential'), ('public', 'Public')], default='confidential', help_text='<b>Confidential</b> clients are capable of maintaining the confidentiality of their credentials. <b>Public</b> clients are incapable.', max_length=30, verbose_name='Client Type')),
                ('client_id', models.CharField(max_length=255, unique=True, verbose_name='Client ID')),
                ('client_secret', models.CharField(blank=True, max_length=255, verbose_name='Client SECRET')),
                ('jwt_alg', models.CharField(choices=[('HS256', 'HS256'), ('RS256', 'RS256')], default='RS256', help_text='Algorithm used to encode ID Tokens.', max_length=10, verbose_name='JWT Algorithm')),
                ('date_created', models.DateField(auto_now_add=True, verbose_name='Date Created')),
                ('website_url', models.CharField(blank=True, default='', max_length=255, verbose_name='Website URL')),
                ('terms_url', models.CharField(blank=True, default='', help_text='External reference to the privacy policy of the client.', max_length=255, verbose_name='Terms URL')),
                ('contact_email', models.CharField(blank=True, default='', max_length=255, verbose_name='Contact Email')),
                ('logo', models.FileField(blank=True, default='', upload_to='oidc_provider/clients', verbose_name='Logo Image')),
                ('reuse_consent', models.BooleanField(default=True, help_text="If enabled, server will save the user consent given to a specific client, so that user won't be prompted for the same authorization multiple times.", verbose_name='Reuse Consent?')),
                ('require_consent', models.BooleanField(default=True, help_text='If disabled, the Server will NEVER ask the user for consent.', verbose_name='Require Consent?')),
                ('_redirect_uris', models.TextField(default='', help_text='Enter each URI on a new line.', verbose_name='Redirect URIs')),
                ('_post_logout_redirect_uris', models.TextField(blank=True, default='', help_text='Enter each URI on a new line.', verbose_name='Post Logout Redirect URIs')),
                ('_scope', models.TextField(blank=True, default='', help_text='Specifies the authorized scope values for the client app.', verbose_name='Scopes')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('owner', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oidc_clients_set', to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
            },
        ),
        migrations.CreateModel(
            name='ResponseType',
            fields=[
                ('value', models.CharField(choices=[('code', 'code (Authorization Code Flow)'), ('id_token', 'id_token (Implicit Flow)'), ('id_token token', 'id_token token (Implicit Flow)'), ('code token', 'code token (Hybrid Flow)'), ('code id_token', 'code id_token (Hybrid Flow)'), ('code id_token token', 'code id_token token (Hybrid Flow)')], max_length=30, unique=True, verbose_name='Response Type Value')),
                ('description', models.CharField(max_length=50)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='RSAKey',
            fields=[
                ('key', models.TextField(help_text='Paste your private RSA Key here.', verbose_name='Key')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'RSA Key',
                'verbose_name_plural': 'RSA Keys',
            },
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('expires_at', models.DateTimeField(verbose_name='Expiration Date')),
                ('_scope', models.TextField(default='', verbose_name='Scopes')),
                ('access_token', models.CharField(max_length=255, unique=True, verbose_name='Access Token')),
                ('refresh_token', models.CharField(max_length=255, unique=True, verbose_name='Refresh Token')),
                ('_id_token', models.TextField(verbose_name='ID Token')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oidc_provider.Client', verbose_name='Client')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Token',
                'verbose_name_plural': 'Tokens',
            },
        ),
        migrations.CreateModel(
            name='Code',
            fields=[
                ('expires_at', models.DateTimeField(verbose_name='Expiration Date')),
                ('_scope', models.TextField(default='', verbose_name='Scopes')),
                ('code', models.CharField(max_length=255, unique=True, verbose_name='Code')),
                ('nonce', models.CharField(blank=True, default='', max_length=255, verbose_name='Nonce')),
                ('is_authentication', models.BooleanField(default=False, verbose_name='Is Authentication?')),
                ('code_challenge', models.CharField(max_length=255, null=True, verbose_name='Code Challenge')),
                ('code_challenge_method', models.CharField(max_length=255, null=True, verbose_name='Code Challenge Method')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oidc_provider.Client', verbose_name='Client')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Authorization Code',
                'verbose_name_plural': 'Authorization Codes',
            },
        ),
        migrations.AddField(
            model_name='client',
            name='response_types',
            field=models.ManyToManyField(to='oidc_provider.ResponseType'),
        ),
        migrations.CreateModel(
            name='UserConsent',
            fields=[
                ('expires_at', models.DateTimeField(verbose_name='Expiration Date')),
                ('_scope', models.TextField(default='', verbose_name='Scopes')),
                ('date_given', models.DateTimeField(verbose_name='Date Given')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oidc_provider.Client', verbose_name='Client')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'unique_together': {('user', 'client')},
            },
        ),
    ]
