# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-08-25 14:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0003_auto_20170808_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='path',
            field=models.TextField(blank=True),
        ),
    ]
