# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-22 13:13
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0005_auto_20171208_1024'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='headers',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
    ]
