# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-07 10:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.OAUTH2_PROVIDER_APPLICATION_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CanvasInstance',
            fields=[
                ('instance_guid', models.CharField(max_length=100)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('applications', models.ManyToManyField(to=settings.OAUTH2_PROVIDER_APPLICATION_MODEL)),
            ],
        ),
    ]
