# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-08-08 16:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0002_action_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='path',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
