# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-08 10:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0004_auto_20170825_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
