# Generated by Django 2.1.8 on 2019-03-15 10:16

import appdj.actions.utils
from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0007_auto_20180913_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='headers',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, encoder=appdj.actions.utils.SkipJSONEncoder),
        ),
        migrations.AlterField(
            model_name='action',
            name='payload',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='action',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions', to=settings.AUTH_USER_MODEL),
        ),
    ]
