# Generated by Django 3.0.5 on 2020-04-22 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djstripe', '0006_2_3'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='illumideskuser',
            options={},
        ),
        migrations.AddField(
            model_name='illumideskuser',
            name='avatar',
            field=models.FileField(blank=True, null=True, upload_to='profile-pictures/'),
        ),
        migrations.AddField(
            model_name='illumideskuser',
            name='customer',
            field=models.ForeignKey(blank=True, help_text="The user's Stripe Customer object, if it exists", null=True, on_delete=django.db.models.deletion.SET_NULL, to='djstripe.Customer'),
        ),
        migrations.AddField(
            model_name='illumideskuser',
            name='subscription',
            field=models.ForeignKey(blank=True, help_text="The user's Stripe Subscription object, if it exists", null=True, on_delete=django.db.models.deletion.SET_NULL, to='djstripe.Subscription'),
        ),
    ]
