# Generated by Django 2.1.8 on 2019-03-15 10:16

import appdj.triggers.models
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('triggers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trigger',
            name='cause',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cause_triggers', to='actions.Action'),
        ),
        migrations.AlterField(
            model_name='trigger',
            name='effect',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='effect_triggers', to='actions.Action'),
        ),
        migrations.AlterField(
            model_name='trigger',
            name='webhook',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=appdj.triggers.models.webhook_default),
        ),
    ]
