# -*- coding: utf-8 -*-
# Generated by Django 1.11.4.dev20170803104644 on 2017-08-03 12:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EnvironmentResource',
            new_name='ServerSize',
        ),
        migrations.RenameField(
            model_name='server',
            old_name='environment_resources',
            new_name='server_size',
        ),
    ]
