# -*- coding: utf-8 -*-
# Generated by Django 1.11.5.dev20170901122659 on 2017-09-01 12:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0004_server_access_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
