# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-11-21 11:32
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0006_auto_20171113_2049'),
        ('servers', '0007_server_last_start'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deployment',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('config', django.contrib.postgres.fields.jsonb.JSONField(default={})),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deployments', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deployments', to='projects.Project')),
            ],
            options={
                'permissions': (('write_server', 'Write server'), ('read_server', 'Read server')),
                'abstract': False,
            },
        ),
    ]
