# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-11-21 14:47
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_auto_20171121_1447'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('servers', '0007_server_last_start'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deployment',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('config', django.contrib.postgres.fields.jsonb.JSONField(default={})),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deployments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('write_server', 'Write server'), ('read_server', 'Read server')),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Framework',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('version', models.CharField(max_length=10)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Runtime',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='deployment',
            name='framework',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deployments', to='servers.Framework'),
        ),
        migrations.AddField(
            model_name='deployment',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deployments', to='projects.Project'),
        ),
        migrations.AddField(
            model_name='deployment',
            name='runtime',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deployments', to='servers.Runtime'),
        ),
    ]
