# -*- coding: utf-8 -*-
# Generated by Django 1.11.7.dev20171128184258 on 2017-11-29 15:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_auto_20171129_1541'),
        ('servers', '0008_merge_20171107_1139'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='server',
            unique_together=set([('project', 'name')]),
        ),
    ]
