# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-11-29 15:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0009_merge_20171128_0832'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deployment',
            name='stage',
        ),
    ]
