# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-04 10:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0010_remove_deployment_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployment',
            name='access_token',
            field=models.TextField(blank=True),
        ),
    ]
