# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-05 15:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0010_auto_20171201_1305'),
        ('servers', '0011_deployment_access_token'),
    ]

    operations = [
    ]
