# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-09-14 09:51
from __future__ import unicode_literals

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0014_auto_20180119_1137'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='server',
            options={},
        ),
        migrations.AddIndex(
            model_name='server',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name'], name='servers_ser_name_9dea9a_gin'),
        ),
    ]
