# Generated by Django 2.1.8 on 2019-03-11 15:36

import django.contrib.postgres.fields.hstore
import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0017_auto_20190311_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deployment',
            name='config',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='server',
            name='config',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='server',
            name='env_vars',
            field=django.contrib.postgres.fields.hstore.HStoreField(default=dict),
        ),
    ]
