# -*- coding: utf-8 -*-
# Generated by Django 1.11.7.dev20180109132606 on 2018-01-09 14:37
from __future__ import unicode_literals

from django.db import migrations, models
import appdj.users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_team_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and - only.', max_length=150, validators=[appdj.users.models.UsernameValidator()], verbose_name='username'),
        ),
    ]
