# Generated by Django 2.2.1 on 2019-07-15 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0003_auto_20190713_0748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='course_id',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='outcome_url',
            field=models.URLField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='path',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='source_did',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='module',
            name='course_id',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='module',
            name='path',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='module',
            name='source_did',
            field=models.TextField(blank=True),
        ),
    ]
