# Generated by Django 2.2.1 on 2019-07-16 11:36

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0019_auto_20190325_1435'),
        ('assignments', '0004_auto_20190715_1002'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProjectThrough',
            fields=[
                ('source_did', models.TextField(blank=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='source_did',
        ),
        migrations.RemoveField(
            model_name='module',
            name='source_did',
        ),
        migrations.AddField(
            model_name='studentprojectthrough',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignments.Assignment'),
        ),
        migrations.AddField(
            model_name='studentprojectthrough',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project'),
        ),
    ]
