# Generated by Django 2.2.1 on 2019-07-16 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0006_auto_20190716_1146'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='student_projects',
            new_name='students_projects',
        ),
    ]
