# Generated by Django 2.2.1 on 2019-10-01 10:46

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0007_auto_20190716_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='endpoint',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='external_id',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='module',
            name='external_id',
            field=models.TextField(blank=True),
        ),
    ]
