# Generated by Django 2.2.1 on 2019-10-07 07:53

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0008_auto_20191001_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='endpoint',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, null=True),
        ),
    ]
