# -*- coding: utf-8 -*-
# Generated by Django 1.11.4.dev20170714110119 on 2017-07-14 15:07
from __future__ import unicode_literals

from django.conf import settings
from django.contrib.postgres.operations import HStoreExtension
import django.contrib.postgres.fields.hstore
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('infrastructure', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0001_initial'),
    ]

    operations = [
        HStoreExtension(),
        migrations.CreateModel(
            name='EnvironmentResource',
            fields=[
                ('name', models.CharField(max_length=50, unique=True)),
                ('cpu', models.IntegerField()),
                ('memory', models.IntegerField()),
                ('description', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField()),
                ('storage_size', models.IntegerField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('private_ip', models.CharField(max_length=19)),
                ('public_ip', models.CharField(max_length=19)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=50)),
                ('container_id', models.CharField(blank=True, max_length=100)),
                ('env_vars', django.contrib.postgres.fields.hstore.HStoreField(default={})),
                ('startup_script', models.CharField(blank=True, max_length=50)),
                ('config', django.contrib.postgres.fields.jsonb.JSONField(default={})),
                ('auto_restart', models.BooleanField(default=False)),
                ('image_name', models.CharField(blank=True, max_length=100)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('connected', models.ManyToManyField(blank=True, related_name='_server_connected_+', to='servers.Server')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servers', to=settings.AUTH_USER_MODEL)),
                ('environment_resources', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servers.EnvironmentResource')),
                ('host', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='servers', to='infrastructure.DockerHost')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servers', to='projects.Project')),
            ],
        ),
        migrations.CreateModel(
            name='ServerRunStatistics',
            fields=[
                ('start', models.DateTimeField(blank=True, null=True)),
                ('stop', models.DateTimeField(blank=True, null=True)),
                ('exit_code', models.IntegerField(blank=True, null=True)),
                ('size', models.BigIntegerField(blank=True, null=True)),
                ('stacktrace', models.TextField(blank=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('server', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='servers.Server')),
            ],
        ),
        migrations.CreateModel(
            name='ServerStatistics',
            fields=[
                ('start', models.DateTimeField(blank=True, null=True)),
                ('stop', models.DateTimeField(blank=True, null=True)),
                ('size', models.BigIntegerField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('server', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='servers.Server')),
            ],
        ),
        migrations.CreateModel(
            name='SshTunnel',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('host', models.CharField(max_length=50)),
                ('local_port', models.IntegerField()),
                ('endpoint', models.CharField(max_length=50)),
                ('remote_port', models.IntegerField()),
                ('username', models.CharField(max_length=32)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servers.Server')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='sshtunnel',
            unique_together=set([('name', 'server')]),
        ),
    ]
