# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-08-25 14:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0003_serversize_cost_per_second'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='access_token',
            field=models.TextField(blank=True),
        ),
    ]
