# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-10-13 12:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0005_server_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='server',
            options={'permissions': (('write_server', 'Write server'), ('read_server', 'Read server'))},
        ),
        migrations.AlterModelOptions(
            name='sshtunnel',
            options={'permissions': (('write_ssh_tunnel', 'Write ssh tunnel'), ('read_ssh_tunnel', 'Read ssh tunnel'))},
        ),
    ]
