# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-07 09:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0006_auto_20171013_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='last_start',
            field=models.DateTimeField(null=True),
        ),
    ]
