# -*- coding: utf-8 -*-
# Generated by Django 1.11.6.dev20171101121058 on 2017-11-01 13:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0006_auto_20171101_1321'),
        ('servers', '0006_auto_20171013_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='serverrunstatistics',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='serverrunstatistics',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='serverrunstatistics',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Project'),
        ),
        migrations.AddField(
            model_name='serverrunstatistics',
            name='server_size_cost_per_second',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='serverrunstatistics',
            name='server_size_is_gpu',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='serverrunstatistics',
            name='server_size_is_metered',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='serverrunstatistics',
            name='server_size_memory',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='serversize',
            name='is_gpu',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='serversize',
            name='is_metered',
            field=models.BooleanField(default=False),
        ),
    ]
