# -*- coding: utf-8 -*-
# Generated by Django 1.11.7.dev20171201120452 on 2017-12-01 13:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0009_auto_20171129_1541'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='server',
            unique_together=set([]),
        ),
    ]
