# -*- coding: utf-8 -*-
# Generated by Django 1.11.7.dev20180109132606 on 2018-01-09 14:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0012_merge_20171205_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='framework',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='runtime',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
