# Generated by Django 2.1.8 on 2019-03-20 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0017_auto_20190315_1016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deployment',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='deployment',
            name='framework',
        ),
        migrations.RemoveField(
            model_name='deployment',
            name='project',
        ),
        migrations.RemoveField(
            model_name='deployment',
            name='runtime',
        ),
        migrations.DeleteModel(
            name='Deployment',
        ),
    ]
