FROM python:3.6-alpine

RUN apk update \
 && apk upgrade \
 && apk add --no-cache \
    build-base \
    git \
    postgresql-dev \
    libffi-dev \
    zlib-dev \
    libjpeg \
    jpeg-dev \
    curl

RUN pip install virtualenv

RUN addgroup -g 1000 -S app && \
    adduser -u 1000 -S app -G app

RUN mkdir -p /workspaces/
RUN mkdir -p /srv/app/staticfiles
RUN chown -R 1000:1000 /workspaces/
RUN chown -R 1000:1000 /srv

USER app

WORKDIR /srv/
RUN virtualenv env --python=python3
RUN . env/bin/activate; pip install --upgrade setuptools pip wheel

COPY --chown=1000:1000 requirements/ /srv/app/requirements

# install requirements to run app
RUN . env/bin/activate; pip install -r app/requirements/dev.txt

COPY --chown=1000:1000 . /srv/app

RUN touch /srv/app/celerybeat.pid

WORKDIR /srv/app

ENTRYPOINT ["/srv/app/docker-entrypoint.sh"]

EXPOSE 8080
