# Generated by Django 2.1.8 on 2019-03-19 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canvas', '0003_canvasinstance_applications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canvasinstance',
            name='instance_guid',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
