# Generated by Django 2.1.8 on 2019-03-19 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('canvas', '0004_auto_20190319_1350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='canvasinstance',
            name='applications',
        ),
    ]
