# -*- coding: utf-8 -*-
# Generated by Django 1.11.4.dev20170803104644 on 2017-08-03 11:07
from __future__ import unicode_literals

from django.db import migrations
import appdj.users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20170727_1035'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', appdj.users.models.CustomUserManager()),
            ],
        ),
    ]
