# Generated by Django 2.1.8 on 2019-03-25 14:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_userprofile_applications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='applications',
            field=models.ManyToManyField(blank=True, related_name='users', to=settings.OAUTH2_PROVIDER_APPLICATION_MODEL),
        ),
    ]
