# Generated by Django 2.2.1 on 2019-05-16 08:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('canvas', '0006_canvasinstance_applications'),
    ]

    operations = [
        migrations.AddField(
            model_name='canvasinstance',
            name='admins',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
