# Generated by Django 2.2.1 on 2019-05-20 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0002_ecscluster'),
        ('canvas', '0008_auto_20190516_0813'),
    ]

    operations = [
        migrations.AddField(
            model_name='canvasinstance',
            name='cluster',
            field=models.ManyToManyField(to='infrastructure.ECSCluster'),
        ),
    ]
