# Generated by Django 2.2.1 on 2019-05-21 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('canvas', '0009_canvasinstance_cluster'),
    ]

    operations = [
        migrations.RenameField(
            model_name='canvasinstance',
            old_name='cluster',
            new_name='clusters',
        ),
    ]
