# Generated by Django 2.2.1 on 2019-07-30 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canvas', '0010_auto_20190521_0921'),
    ]

    operations = [
        migrations.AddField(
            model_name='canvasinstance',
            name='oidc_auth_endpoint',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='canvasinstance',
            name='oidc_jwks_endpoint',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='canvasinstance',
            name='oidc_token_endpoint',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='canvasinstance',
            name='oidc_user_endpoint',
            field=models.URLField(blank=True),
        ),
    ]
