# Generated by Django 2.2.1 on 2019-10-08 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canvas', '0011_auto_20190730_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='canvasinstance',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
