# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-09-14 09:36
from __future__ import unicode_literals

from django.db import migrations
from django.contrib.postgres.operations import BtreeGinExtension, TrigramExtension, UnaccentExtension


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        BtreeGinExtension(),
        TrigramExtension(),
        UnaccentExtension(),
    ]
