# Generated by Django 2.1.8 on 2019-03-11 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0002_logentry_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logentry',
            name='action_flag',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Addition'), (2, 'Change'), (3, 'Deletion')], verbose_name='action flag'),
        ),
    ]
