# -*- coding: utf-8 -*-
# Generated by Django 1.11.7.dev20171107113843 on 2017-11-07 11:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0007_server_last_start'),
        ('servers', '0007_auto_20171101_1321'),
    ]

    operations = [
    ]
