# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-11-28 08:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0008_auto_20171124_1024'),
        ('servers', '0008_merge_20171107_1139'),
    ]

    operations = [
    ]
