# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-01-19 11:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0013_auto_20180109_1437'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deployment',
            options={'permissions': (('start_server', 'Start server'), ('stop_server', 'Stop server'), ('write_server', 'Write server'), ('read_server', 'Read server'))},
        ),
        migrations.AlterModelOptions(
            name='server',
            options={'permissions': (('start_server', 'Start server'), ('stop_server', 'Stop server'), ('write_server', 'Write server'), ('read_server', 'Read server'))},
        ),
    ]
