# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-09-14 11:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0015_auto_20180914_0951'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='server',
            options={'permissions': (('start_server', 'Start server'), ('stop_server', 'Stop server'), ('write_server', 'Write server'), ('read_server', 'Read server'))},
        ),
    ]
