# Generated by Django 2.1.8 on 2019-03-20 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0018_auto_20190320_1102'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sshtunnel',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='sshtunnel',
            name='server',
        ),
        migrations.DeleteModel(
            name='SshTunnel',
        ),
    ]
