# Generated by Django 2.2.1 on 2019-05-15 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0019_auto_20190320_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='serverrunstatistics',
            name='container_id',
            field=models.TextField(blank=True),
        ),
    ]
