# Generated by Django 2.2.1 on 2019-05-16 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0020_serverrunstatistics_container_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serverrunstatistics',
            options={'permissions': (('generate_report', 'Generate usage report'),)},
        ),
    ]
