# Generated by Django 2.2.1 on 2019-05-16 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0021_auto_20190516_0803'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serverrunstatistics',
            options={},
        ),
    ]
