# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-10-30 12:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import social_django.fields


class Migration(migrations.Migration):

    dependencies = [
        ('social_django', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='code',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partial',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='partial',
            name='data',
            field=social_django.fields.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='usersocialauth',
            name='extra_data',
            field=social_django.fields.JSONField(default=dict),
        ),
    ]
