# Generated by Django 2.1.8 on 2019-03-13 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth2_provider', '0002_auto_20190311_1536'),
    ]

    operations = [
        migrations.RunSQL("ALTER TABLE oauth2_provider_accesstoken ADD COLUMN new_id BIGSERIAL"),
        migrations.RunSQL("ALTER TABLE oauth2_provider_accesstoken DROP CONSTRAINT oauth2_provider_accesstoken_pkey CASCADE"),
        migrations.RunSQL("ALTER TABLE oauth2_provider_accesstoken DROP COLUMN id"),
        migrations.RunSQL("ALTER TABLE oauth2_provider_accesstoken RENAME COLUMN new_id TO id"),
        migrations.RunSQL(
            "ALTER TABLE oauth2_provider_accesstoken ADD PRIMARY KEY (id)",
            state_operations=[
                migrations.AlterField(
                    model_name='accesstoken',
                    name='id',
                    field=models.BigAutoField(primary_key=True, serialize=False),
                ),
            ]
        ),
        migrations.RunSQL("ALTER TABLE oauth2_provider_application ADD COLUMN new_id BIGSERIAL"),
        migrations.RunSQL("ALTER TABLE oauth2_provider_application DROP CONSTRAINT oauth2_provider_application_pkey CASCADE"),
        migrations.RunSQL("ALTER TABLE oauth2_provider_application DROP COLUMN id"),
        migrations.RunSQL("ALTER TABLE oauth2_provider_application RENAME COLUMN new_id TO id"),
        migrations.RunSQL(
            "ALTER TABLE oauth2_provider_application ADD PRIMARY KEY (id)",
            state_operations=[
                migrations.AlterField(
                    model_name='application',
                    name='id',
                    field=models.BigAutoField(primary_key=True, serialize=False),
                ),
            ]
        ),
        migrations.RunSQL("ALTER TABLE oauth2_provider_grant ADD COLUMN new_id BIGSERIAL"),
        migrations.RunSQL("ALTER TABLE oauth2_provider_grant DROP CONSTRAINT oauth2_provider_grant_pkey CASCADE"),
        migrations.RunSQL("ALTER TABLE oauth2_provider_grant DROP COLUMN id"),
        migrations.RunSQL("ALTER TABLE oauth2_provider_grant RENAME COLUMN new_id TO id"),
        migrations.RunSQL(
            "ALTER TABLE oauth2_provider_grant ADD PRIMARY KEY (id)",
            state_operations=[
                migrations.AlterField(
                    model_name='grant',
                    name='id',
                    field=models.BigAutoField(primary_key=True, serialize=False),
                ),
            ]
        ),
        migrations.RunSQL("ALTER TABLE oauth2_provider_refreshtoken ADD COLUMN new_id BIGSERIAL"),
        migrations.RunSQL("ALTER TABLE oauth2_provider_refreshtoken DROP CONSTRAINT oauth2_provider_refreshtoken_pkey CASCADE"),
        migrations.RunSQL("ALTER TABLE oauth2_provider_refreshtoken DROP COLUMN id"),
        migrations.RunSQL("ALTER TABLE oauth2_provider_refreshtoken RENAME COLUMN new_id TO id"),
        migrations.RunSQL(
            "ALTER TABLE oauth2_provider_refreshtoken ADD PRIMARY KEY (id)",
            state_operations=[
                migrations.AlterField(
                    model_name='refreshtoken',
                    name='id',
                    field=models.BigAutoField(primary_key=True, serialize=False),
                ),
            ]
        ),
    ]
