# -*- coding: utf-8 -*-
# Generated by Django 1.11.6.dev20170919160255 on 2017-09-20 15:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationtype',
            name='entity',
            field=models.CharField(default='', max_length=25),
            preserve_default=False,
        ),
    ]
