# -*- coding: utf-8 -*-
# Generated by Django 1.11.6.dev20170922133550 on 2017-09-25 12:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notificationtype_entity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationtype',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
