# -*- coding: utf-8 -*-
# Generated by Django 1.11.6.dev20170926112017 on 2017-09-26 11:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0001_initial'),
        ('users', '0003_auto_20170803_1107'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notifications', '0003_auto_20170925_1244'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationSettings',
            fields=[
                ('entity', models.CharField(max_length=50)),
                ('object_id', models.UUIDField(null=True)),
                ('enabled', models.BooleanField(default=True)),
                ('emails_enabled', models.BooleanField(default=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email_address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Email')),
                ('object_content_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='notification',
            name='action_object_content_type',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='action_object_object_id',
        ),
    ]
