# -*- coding: utf-8 -*-
# Generated by Django 1.11.6.dev20170926112017 on 2017-09-26 14:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_auto_20170926_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationtype',
            name='subject',
            field=models.CharField(default='', max_length=75),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notificationtype',
            name='template_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
