# -*- coding: utf-8 -*-
# Generated by Django 1.11.6.dev20170926171112 on 2017-09-26 17:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_auto_20170926_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
