# -*- coding: utf-8 -*-
# Generated by Django 1.11.6.dev20170927122113 on 2017-09-27 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0007_auto_20170926_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationtype',
            name='entity',
            field=models.CharField(max_length=50),
        ),
    ]
