# -*- coding: utf-8 -*-
# Generated by Django 1.11.6.dev20170928164216 on 2017-09-28 16:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0008_auto_20170927_1414'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='public',
        ),
    ]
