# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-11-21 14:47
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20171113_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(re.compile('^[-\\w]+\\Z', 32), "Enter a valid 'slug' consisting of Unicode letters, numbers, underscores, or hyphens.", 'invalid')]),
        ),
    ]
