# -*- coding: utf-8 -*-
# Generated by Django 1.11.7.dev20171121124756 on 2017-11-21 12:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_project_is_active'),
        ('projects', '0006_auto_20171113_2049'),
    ]

    operations = [
    ]
