# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-01-16 12:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_auto_20180116_1135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='integrations',
        ),
    ]
